package com.intro2se.yummy.enums;

public enum OrderStatus {
    WAITING_RESTAURANT_CONFIRMATION,
    RESTAURANT_CONFIRMED,
    WAITING_DRIVER_CONFIRMATION,
    DRIVER_CONFIRMED,
    WAITING_DELIVERY,
    DELIVERING,
    DELIVERED,
    CANCELLED
}
