ALTER TABLE ORDERS
MODIFY COLUMN order_status ENUM(
    'WAITING_RESTAURANT_CONFIRMATION',
    'RESTAURANT_CONFIRMED',
    'WAITING_DRIVER_CONFIRMATION',
    'DRIVER_CONFIRMED',
    'WAITING_DELIVERY',
    'DELIVERING',
    'DELIVERED',
    'CANCELLED'
) NOT NULL;
